name: Test Mask Scripts

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libglib2.0-0 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-xinput0 \
            libxcb-xfixes0 \
            libopengl0

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Clone RVS-A_mask_scripts (matching branch)
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Pulling branch: $BRANCH from RVS-A_mask_scripts"
          git clone --single-branch --branch "$BRANCH" https://github.com/rayngrowingsystems/RVS-A_mask_scripts.git Application/Masks \
            || git clone --single-branch --branch main https://github.com/rayngrowingsystems/RVS-A_mask_scripts.git Application/Masks

      - name: Clone RVS-A_analysis_scripts (matching branch)
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Pulling branch: $BRANCH from RVS-A_analysis_scripts"
          git clone --single-branch --branch "$BRANCH" https://github.com/rayngrowingsystems/RVS-A_analysis_scripts.git Application/Scripts \
            || git clone --single-branch --branch main https://github.com/rayngrowingsystems/RVS-A_analysis_scripts.git Application/Scripts

      - name: Run tests
        run: |
          pytest tests/test_scripts.py --maxfail=1 --disable-warnings -q
